### ISSUE TITLE
求kindle版本

### ISSUE THREAD

**Issue by le02611** [waylau/gradle-3-user-guide#1]
真的很赞 翻译的非常好 我有个小小的请求 能不能制作kindle版本的书 比如mobi格式 很多人需要这个 谢谢

**Comment by waylau** [comment]
@le02611   感谢您的反馈。目前在 Gitbook 上发布的版本  http://waylau.gitbooks.io/gradle-3-user-guide/ ，可以提供` 常见电子书格式的的下载
