### ISSUE TITLE
关于翻译进度

### ISSUE THREAD

**Issue by sheldonshen** [waylau/gradle-3-user-guide#2]
你好,老卫,最近在学gradle,看到你的中文用户指南翻译,我有几个疑问,望解答,1 现在gradle的最新版本是4.0.2,有打算升级到最新版本吗?  2 现在的gradle3的翻译好像后面没有翻译完,请问还会继续吗？ 谢谢.

**Comment by waylau** [comment]
@sheldonshen   感谢您的关注！  gradle  的翻译是会继续的，而且会紧跟版本。鉴于限制 Gradle 官方发布速度有点快，本项目也在调增节奏~看是否是按照分支来区别，还是按照项目来区别不同的版本。 不过还好，整体 Gradle 的用法都差不多。所以在新版的翻译没有出之前，可以先看下老版本的翻译，谢谢
